### PR TITLE
Bug/30 update logos

### LINKED ISSUE #30: Update logos
Fix Pentaho plugin's footer ("2014" and old NP logo)

### PR DESCRIPTION
**Pull request by ClaudiaPHI**
Fixes #30 

Things done: 
-  changed the logos 
-  set the dialog windows in the center of the screen 
-  added "Cancel" and "OK" button  with images for DC Configuration Dialog

image

image

### CODE REVIEW

**Comment by kaspersorensen** [comment]
In the DC splash screen we use this which looks a lot better:

image

Notice the background color is not 100% black. So maybe also the copyright image needs a change.

**Comment by ClaudiaPHI** [comment]
ok. I will replace with these logo.

**Comment by ClaudiaPHI** [comment]
2016-02-09 10_56_55-spoon - kettlejob
2016-02-09 10_57_59-datacleaner configuration

**Comment by kaspersorensen** [comment]
Looks great :)

**Pull request merged**
